### ISSUE TITLE
Issue running in a few scenes

### ISSUE THREAD

**Issue by peros550** [Hypfer/hass-scene_presets#11]
First, let me congratulate you for your idea and efforts in bringing these scenes in HA. 

I have some old Hue bulbs, but when they fail I choose to replace them with Wiz , which also come from same company (Signify) at a much affordable price. The one thing missing was scenes and interoperability with older bulbs, and I just found your integration and gave it a try. 

Running the scenes against Wiz bulbs,  the colors do not match the picture. They tend to stuck in a range of white.  

And in a few scenes (Motown, Tokyo, , I got the following error : 

```
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 6:50:37 PM (1 occurrences)
Last logged: 6:50:37 PM

Error setting up entry scene_presets for scene_presets
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/scene_presets/__init__.py", line 178, in async_setup_entry
    await async_setup_view(hass)
  File "/config/custom_components/scene_presets/view.py", line 25, in async_setup_view
    hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 303, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel scene_presets
```

If you need me to provide more logs, let me know.

Thanks

**Comment by Hypfer** [comment]
The logs are entirely unrelated to any interaction in the UI including any specific scenes.

Have you set up multiple config entries?
Because that's what triggers the logline for me and sounds plausible as something that might happen by accident.
![image](https://github.com/Hypfer/hass-scene_presets/assets/974410/5b34691b-1a91-442b-bacf-1d4dd175fe92)

As for the Wiz bulbs.. yeah. I'm not surprised that different Vendors use different LEDs with different calibration and thus don't have matching colors. This is nothing new, unusual or related to this custom component.

**Comment by peros550** [comment]
OK removed the extra service and restarted HA. 

I get the following message sometimes as a notification "Failed to call service scene_presets/apply_preset. value must be at least 0 for dictionary value @ data['kelvin']"

Any way to make the colors work for Wiz bulbs? Something I can do on my end?

**Comment by Hypfer** [comment]
Colors don't work at all? I understood the description as "Colors are not exactly the same between Wiz and Hue".

Can you share a screenshot of one of those wiz lights in the devtools view including all attributes on the right?

**Comment by peros550** [comment]
thanks for taking the time to look into this.  Here are the states from dev screen.

```
`min_color_temp_kelvin: 2202
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 454
effect_list:
  - Ocean
  - Romance
  - Sunset
  - Party
  - Fireplace
  - Cozy
  - Forest
  - Pastel Colors
  - Wake up
  - Bedtime
  - Warm White
  - Daylight
  - Cool white
  - Night light
  - Focus
  - Relax
  - True colors
  - TV time
  - Plantgrowth
  - Spring
  - Summer
  - Fall
  - Deepdive
  - Jungle
  - Mojito
  - Club
  - Christmas
  - Halloween
  - Candlelight
  - Golden white
  - Pulse
  - Steampunk
  - Rhythm
supported_color_modes:
  - color_temp
  - rgbw
color_mode: color_temp
brightness: 135
color_temp_kelvin: 2932
color_temp: 341
hs_color:
  - 27.941
  - 58.774
rgb_color:
  - 255
  - 174
  - 105
xy_color:
  - 0.503
  - 0.383
rgbw_color: null
effect: null
friendly_name: Desk Light
supported_features: 4`
```
<img width="454" alt="image" src="https://github.com/Hypfer/hass-scene_presets/assets/12878906/2f5f3330-7e98-4c79-aac0-f9d18a666efb">
<img width="1693" alt="image" src="https://github.com/Hypfer/hass-scene_presets/assets/12878906/b3013c91-a152-495f-883a-25219d244872">

**Comment by Hypfer** [comment]
Oooh so that's what that was about with that person that mentioned something about rgbw.

Okay, so lights with a `color_mode` of `rgbw` exist.
The code currently only checks for `xy`, `hs` and `rgb` and if those don't exist, it will check for `color_temp` and attempt to convert the rgb color to a color temperature.

That's why you only get shades of white.
This conversion code isn't clamping the output value properly and that's where this kelvin error message is coming from.

Regarding the Wiz bulbs:
What I can do is add `rgbw` to the list of `supported_color_modes` that allow color.
However since I don't have an `rgbw` bulb, I don't know if that's enough or if it will require to also send a w value of 0 or something like that.


That's something you can test though.

```yaml
service: light.turn_on
target:
  entity_id: light.<wiz_bulb>
data:
  xy_color:
    - 0.1461
    - 0.3543
```

Running this should turn the light turquoise. Does that work? Does that work coming from different states (previous state being off, just a color, a color with white, only white)?

**Comment by peros550** [comment]
yes! it worked. turquoise! Any kind of further test, more than happy to run.

**Comment by Hypfer** [comment]
Please try version 1.1.2 that was just released. _Hopefully_ that should fix everything

**Comment by peros550** [comment]
Many thanks! It works nice ! :)
