### ISSUE TITLE
Other users can't see Scene Presets

### ISSUE THREAD

**Issue by bkscreamer** [Hypfer/hass-scene_presets#14]
I am having trouble getting other users to see Scene Presets in their sidebars, as well as through a dashboard button that links to that page via nav. Is this intentional? Would love to let my other users set scenes in our home, but only I, the admin our our HAOS instance, can see it.

**Comment by Hypfer** [comment]
> Is this intentional?

Nope. Thanks for pointing that out
It's just a setting that was set incorrectly likely because I copy-pasted stuff from components that should be admin only.
I then didn't notice because I'm the only user of my instance. Super simple fix:
https://github.com/Hypfer/hass-scene_presets/commit/6d3458512db78163b2b32ce67cf6562c06e13932

and fixed with 1.2.1

**Comment by bkscreamer** [comment]
Thanks!
