### ISSUE TITLE
Christmas Scenes

### ISSUE THREAD

**Issue by Airler** [Hypfer/hass-scene_presets#6]
Hi,

are there already any considerations about including the christmas scenes from hue?

**Comment by Hypfer** [comment]
Do you see them in the App? Because I don't and that voids the premise of this question.
How could anyone include scenes that don't exist?

Feel free to join the others and annoy the hue support account instead. They're at least being paid to deal with it.
https://twitter.com/tweethue/status/1730918840186401262


But yes, of course I want to add them. It annoys me greatly that a feature that is just
`Array<{name: string, bri: number, colors: Array<{x: number, y: number}>}>`
can be "seasonal" and not available year-round on a physical product that you bought.

But I can't because they're not available. Which makes this whole issue quite pointless.

Here's how a better issue could've looked like:

>Hey, in case you didn't see it, I just wanted to mention that Signify just released the Christmas scenes.
>
> Since you've been adding all the other sets, I thought that you might be interested in that as well; especially since it took quite a while this year and you thus might've missed it.
>
> Cheers!

An issue like that demonstrates that some thought went into the topic. It's somewhat actionable.
It sorta provides some value. (Though only if a few days have passed since that release and I _actually_ missed it)

This issue on the other hand doesn't do that.
It's just "I want christmas scenes!".

Which, yeah, understandable and all. I too want them, but I never signed up to work in a tech enthusiast online daycare.
Please direct your emotional support needs elsewhere.
